version: '3.8'

services:
  
  # Redpanda broker - https://redpanda.com/
  # by default, redpanda will create a topic for us when the producer starts sending events
  redpanda:
    image: redpandadata/redpanda:v23.2.26
    container_name: communicatio-redpanda-broker
    hostname: redpanda
    command:
      - redpanda start
      - --smp 1
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 28082:28082
      - 29092:29092
    volumes:
      - redpanda-data:/var/lib/redpanda/data

  producer:
    image: communicatio-producer
    container_name: communicatio-producer

    build:
      context: ./Producer
      dockerfile: ./Producer/Dockerfile
    
    depends_on:
      - redpanda
  
  consumer:
    image: communicatio-consumer
    container_name: communicatio-consumer

    build:
      context: ./Consumer
      dockerfile: ./Consumer/Dockerfile
    
    depends_on:
      - redpanda

volumes:
  redpanda-data: